// Generated by scripts/libreoffice-asset-version.mjs - do not edit by hand.
// Derived from the contents of public/libreoffice-wasm/, so the ?v= cache key (served with
// Cache-Control: immutable) rolls over whenever the engine files change.
// Regenerate with: node scripts/libreoffice-asset-version.mjs --write

export const LIBREOFFICE_PACKAGE_VERSION = '2.7.2';
export const LIBREOFFICE_ASSET_VERSION = '2.7.2-9cfdb5bcbc3c';
